# Generated by Django 5.0.4 on 2024-04-15 10:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_comment_product_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(choices=[(5, 'EXCELLENT'), (4, 'GOOD'), (3, 'NOT BAD'), (2, 'BAD'), (1, 'VERY BAD')], verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='comment text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
