# Generated by Django 5.0.4 on 2024-05-22 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
