# Generated by Django 5.0.4 on 2024-06-02 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_blog_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_bio',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='author bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='quote'),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote_author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='quote author'),
        ),
    ]
